### ISSUE TITLE
Tekija/kirjoittaja validointi

### ISSUE THREAD

**Issue by metinen** [mkmoisio/ohtu-miniprojekti#17]
Kirjoitin Vinkkitietokanta.javaan kommenttina SQL-komentoja tietokannan rakenteen muutokseen jälkeen (=lisää tauluja).
Listauskomennot eivät toimi oikein jos tietokannassa ei ole arvoa tekijälle/kirjailijalle/kirjoittajalle (kannassa taulu Tekija).
Tämä tulee kirjojen ja podcastien osalta varmaan huomioitua normaalin käyttäjäsyötteen validoinnin kautta kun käyttäjä lisää vinkkiä. Mutta video-tyyppisessä vinkissä on myös pakko olla tekijä. Jollei tätä kysytä käyttäjältä niin koodissa pitää lisätä tekijä, esim. 'tuntematon'. Sitä ei tarvi koskaan näyttää käyttäjälle mutta pitää olla taustalla. Sen takia myös kutsun taulua Tekija, koska on yleisempi termi kuin kirjoittaja

**Comment by thvaisa** [comment]
Muutin sql-komentoja hieman ja sain toimimaan ilman tekijoitä. 
```
"SELECT vinkki.otsikko, vinkki.luettu, kirja.isbn, kirja.kuvaus, group_concat(tekija_nimi, ' ') as tekijat \n"
                                  +  "FROM Vinkki \n"
                                  +  "INNER JOIN kirja ON vinkki_id=kirja.vinkki \n"
                                  +  "LEFT OUTER JOIN VinkkiTekija on vinkki_id=vinkkitekija.vinkki \n"
                                  +  "LEFT OUTER JOIN Tekija on tekija_id=tekija \n"
                                  +  "GROUP BY vinkki_id";
```

**Comment by metinen** [comment]
Joo. Mutta saatko tolla siis listattua kaikentyyppiiset vinkit: eli mukaan kirjat, videot ja podcastit? Haet tuossa vain kirjoja

**Comment by thvaisa** [comment]
Siellä koodissa on nyt niin, että HaeKaikki() käyttää kolme funkiota HaeKaikkiKirjat(Lukustatus), HaeKaikkiPodcast(Lukustatus) (ei implementoitu), HaeKaikkiVideo(Lukustatus) (ei implementoitu), eli ei ole yhteistä SQL-hakukutsua. 

Muuten tuolla saa listattua kaikki ominaisuuksineen. SQLfiddle syrjii mua ja sqlonline on kaatunut, joten en pääse testaamaan esimerkkiä.

**Comment by metinen** [comment]
Ok! En tiedä, tulee kolme hakua tietokannasta vs. yksi.  Mut jätetään mun puolesta niin kuin se nyt on kun meillä molemmilla tunnitkin täynnä ja varmaan hyvä ajatus sulla siinä takana
