### ISSUE TITLE
Tietokanta

### ISSUE THREAD

**Issue by thvaisa** [mkmoisio/ohtu-miniprojekti#23]
Eikö Podcast-taulu pitäisi olla
`CREATE TABLE Podcast (podcast_id integer PRIMARY KEY, nimi text(100), kuvaus text (500), vinkki UNIQUE, FOREIGN KEY (vinkki) REFERENCES Vinkki(vinkki_id)ON DELETE CASCADE );`
eikä
`CREATE TABLE Podcast (podcast_id integer PRIMARY KEY, nimi text(100), kuvaus text (500), vinkki UNIQUE, FOREIGN KEY (vinkki) REFERENCES Vinkki(vinkki)ON DELETE CASCADE );?`

**Comment by metinen** [comment]
Joo pitäis, hyvin huomattu. Jännää, että tähän mennessä on toiminut kuitenkin tai huomasitko jostain virheestä?

**Comment by thvaisa** [comment]
Tein testejä ja huomasin, ettei poistot toiminut. Laitoin sitten ne foreign key:t päälle ja sitten Podcastiin liittyvät testit hajosi. Ero löytyi vertaamalla tauluja Kirja ja Podcast. Väärä taulu on vielä olemassa sprint2testikanna.db:ssä. Katon myöhemmin kuinka saan korjattua taulun ja siirrettyä datan
