### ISSUE TITLE
Meidän koodin logiikka 

### ISSUE THREAD

**Issue by metinen** [mkmoisio/ohtu-miniprojekti#29]
Periaatteessa tagien lisäys noudattaa samaa kaavaa kuin tekijöiden lisäys. Nyt täytyy sanoa että en seuraa meidän koodin logiikkaa etenkin kun poistuu Käyttöliittymästä niin on tietokantahakuja ja logiikkaa lähes kaikki vain kahdessa luokassa Vinkkitietokanta ja Vinkki, ja hyvin samannimisiä metodeja peräkkäin? Yritin vähän sisustaa  Vinkkitietokanta-luokkaa mutta aika rupeaa loppumaan ja aikaa menis ihan metodien dokumentointiin ettei ajatus katkeis koko ajan. Tagien osalta abstraktoin tietokantahaut TagDAO:on mutta mun kysymys liittyy siis siihen kun yritän liittää tätä koodiimme, häviän sinne tän sprintin ajan puitteissa..Sain viime sprintissä lisättyä video-toiminnallisuuden mutta tämä on laajempi niin rupeaa jo merkkaamaan miten pitkä ja täynnä kaikenlaista yksi ja sama luokka on. 

Kysymys tekijöiden lisäämisestä (jota tagien lisäys ois tarkoitus peilata): onko nämä siis käsitelty ikäänkuin kaikki tekijät tulevat käyttäjältä yhtenä Stringinä sisään? Voisiko ne jo syöttövaiheesa kerätä listaan, ettei tarvi myöhemmin veivata Vinkki-luokassa? 

Lisäksi miksi tämä?:
 private void liitaTekija(String vinkkiID, String tekijaID) {
        String lisaaVinkkiin = "INSERT INTO VinkkiTekija (vinkki,tekija) VALUES (?,?)";
        try {
            this.avaaYhteys();
            PreparedStatement komento = conn.prepareStatement(lisaaVinkkiin);
            komento.setInt(1, Integer.parseInt(vinkkiID));
            komento.setInt(2, Integer.parseInt(tekijaID));
Eli on käsitely koodissa vinkkiID ja tekijaID stringeinä ja sit kun viedään kantaan niin muunnetaan integereiksi, mitä ne ovatkin siellä. Miksi niitä ylipäänsä on käsitelty Stringeinä sitä ennen?

Mun tarkoitus tässä siis on vaan kysyä että saadaan tää maaliin.

Pushasin rikkänäisen koodin joka on sekoitusta miten lähdin tekemään ja miten tulkitsin olemassaolevaa rakennetta, että saisin feedbackia. Voin tulla yliopistolle iltapäivästä jos ootte siellä. Tai jos tekijät -toiminnallisuuden tehnyt hoitaa tämän nopeasti niin ole hyvä ja kiitos ja vois ens sprinttiin sit ottaa koodin refaktorointia luettavuuden lisäämiseksi? 

Mulla ei tule riittämään aika testeille.

**Comment by thvaisa** [comment]
>integereiksi, mitä ne ovatkin siellä. Miksi niitä ylipäänsä on käsitelty Stringeinä sitä ennen?
Koska ajattelin alunperin, että ID:t pitäisi olla merkkijonoina, koska antaa laajemman alueen (0000-9999 vs. 0000-XXXX). Myöhemmin huomasin, että tauluissa ne ovatkin kokonaislukuja. Ei tuossa pitäisi olla mitään ongelmaa muuten.

**Comment by thvaisa** [comment]
Joo tuo tuottaa nyt hirveitä ongelmia, että käytetään näitä LisääKirja(asd,asd,asd). Kannattaa tehdä niin, että käyttöliittymä luo aina Vinkin, johon lisätään tarvittavia ominaisuuksia, tageja, tekijöitä. Sen jälkeen kutsutaan Vinkkitietokannan lisääVinkki, joka hoitaa loput.

**Comment by thvaisa** [comment]
Sitä varten se Vinkki luotiin, että tiedonsiirto käyttöliittymän ja Vinkkitietokannan välillä on "helppoa", Noiden "legacy" funktioiden "lisääKirja(otsikko, nimi)" käyttäminen aiheuttaa sen, että aina kun tulee uusi ominaisuus, niin funktioita jatketaan N määrällä argumentteja.

**Comment by thvaisa** [comment]
Korjasin käyttöliittymän ja siirsin rikkinäisen commitin omaan haaraan. Olen iltapäivällä yliopistolla, joten laita viestiä kun olet paikalla.

**Comment by metinen** [comment]
Ok katon vielä lounaalla vähän ja yritän livahtaa mahd ajoissa töistä. Neljän jälkeen on kuitenkin onko ok?

**Comment by thvaisa** [comment]
joo

**Comment by metinen** [comment]
Oon yliopistolla 16:05 jos nähdään physicum ovilla/aulassa Toivottavasti on ovet vielä auki, mulla ei ole kulkulupaa.
