### ISSUE TITLE
KIIRE tietokanta jariin ongelma

### ISSUE THREAD

**Issue by metinen** [mkmoisio/ohtu-miniprojekti#47]
Kuka ratkaisi tämän viime sprintissä? Tein macilla. Mulla myös tunnit täynnä ja olen nyt töissä, ei aikaa tutkia sen enempää kuin muilla. Viime viikon mailikeskutelusta en löydä samasta ongelmasta ratkaisun kuvausta, vain keskustelua ennen ja Timo taisi todeta jälkeenpäin että nyt toimii, eli Timo miten ratkaisit tämän?
 
$ java -jar ohtu-miniprojekti.jar 
Exception in thread "main" java.lang.NoClassDefFoundError: org/sqlite/SQLiteConfig
	at Vinkkitietokanta.Vinkkitietokanta.<init>(Vinkkitietokanta.java:37)
	at Main.main(Main.java:12)
Caused by: java.lang.ClassNotFoundException: org.sqlite.SQLiteConfig
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 2 more

**Comment by metinen** [comment]
huomaan että ilmeisesti ratkaistu viime viikolla käyttämällä shadow-pluginia?

Mutta mulle ei ilmesty gradle jarilla tuota all- jaria? build/libs alle tulee vaan normaali .jar joka tosiaan antaa viime viestin mukaisen virheviestin

If working with a Gradle project with the name myApp and version 1.0, the default shadowJar task will output a file at: build/libs/myApp-1.0-all.jar

**Comment by metinen** [comment]
Mulla ei näy gradle tasks komennolla Shadow taskeja eli siksi mulle ei muodostu tuota shadow.jaria. En nyt edes ole varman onko viime viikolla käytetty shadowia tai ei.

Jostain syystä meillä on githubissa kaksi tiedostoa build.gradle (jossa poissa shadow plugin) ja build.gradle<aalto>, jossa shadow-plugin. Olen kokeillut molempien ollessa ainoa aktiivinen build.gradle (uudelleennimesin silloin build.gradle<aalto> build.gradleksi)

En ole nimetty demon hoitaja muutoin kuin viime yön nakituksessa ja tässä vaiheessa ois tärkeä että joku, joka on onnistunut tämän sprint3 tekemään veisi tämän maaliin niillä tiedoilla, jotka hänellä on viime viikon perusteella?

**Comment by mkmoisio** [comment]
Kokeilkaa toimiiko:
https://github.com/mkmoisio/ohtu-miniprojekti/releases/tag/v0.9-pre

**Comment by mkmoisio** [comment]
Ja joo, toi sun alkuperäinen ongelma on siitä, ettet käyttänyt shadow-pluginia. Shadow-pluginissa taas oli joku sellanen probleema, että gradlen versio on liian vanha shadow-pluginille tms, jonka vuoksi Travis sekoaa jos pushaa sen build.gradlen missä se shadow-plugin on päällä. Ongelma on "ratkaistu" niin, että shadow-plugin kytketään päälle vain siksi aikaa kun se jar luodaan.

**Comment by metinen** [comment]
Joo jar toimii nyt mulla (macilla). Tuutko demoon?

**Comment by mkmoisio** [comment]
Tuun joo. Haluaisitko olla demoaja? Mä en nimittäin ihan hirveästi innostu siitä roolista..

**Comment by metinen** [comment]
Joo. oon täällä auditoriossa
