### ISSUE TITLE
MuunnaVinkkiä-toiminnallisuus

### ISSUE THREAD

**Issue by metinen** [mkmoisio/ohtu-miniprojekti#49]
Ei demottu muunnaVinkkiä kun se puuttui komentolistauksesta (ainakin siinä versiossa mikä demottiin oli pieni bugi). Pushasin juuri muutoksen että näkyy komentona.

Mutta kun testasin tätä toimintoa muuttamalla videon urlia sain virheilmoituksen, eli hyvä vain että jäi demoamatta (vaihtaa kyllä urlin kannassa oikein):

liitaTag: [SQLITE_CONSTRAINT]  Abort due to constraint violation (UNIQUE constraint failed: VinkkiTag.vinkki, VinkkiTag.tag)
liitaTag: [SQLITE_CONSTRAINT]  Abort due to constraint violation (UNIQUE constraint failed: VinkkiTag.vinkki, VinkkiTag.tag)
liitaTag: [SQLITE_CONSTRAINT]  Abort due to constraint violation (UNIQUE constraint failed: VinkkiTag.vinkki, VinkkiTag.tag)
liitaTag: [SQLITE_CONSTRAINT]  Abort due to constraint violation (UNIQUE constraint failed: VinkkiTag.vinkki, VinkkiTag.tag)
liitaTag: [SQLITE_CONSTRAINT]  Abort due to constraint violation (UNIQUE constraint failed: VinkkiTag.vinkki, VinkkiTag.tag)
liitaTag: [SQLITE_CONSTRAINT]  Abort due to constraint violation (UNIQUE constraint failed: VinkkiTag.vinkki, VinkkiTag.tag)

Haluatko Timo vielä korjata tai jätetäänkö pois sprintistä?

**Comment by thvaisa** [comment]
Tarkistan asian

**Comment by thvaisa** [comment]
Virhe oli siinä, ettei Vinkki-luokka osannut lukea tageja vinkkitietokannasta tulevasta merkkijonosta. Sinne tulee mukaan kaikenlaisia tyhjiä tageja jne.. Luulen, että ongelmana, ettei erotin "----" toimi niin kuin oletettu. Korjasin ongelman samalla tavalla kuin tekijöiden kanssa, ei hyväksytä tyhjiä merkkijonoja.
