### ISSUE TITLE
Taulukot

### ISSUE THREAD

**Issue by thvaisa** [mkmoisio/ohtu-miniprojekti#5]
Onko ne taulukot missä kunnossa?

**Comment by metinen** [comment]
Huomasin nyt. Tein äsken mergen ja siinä taulut sekä doc-kansiossa tietokantamalli (sprint1 laajuudessa taulut sekä hieman lisähahmotelmaa). Huomasin äsken myös issuen kielestä ja tein tietokannan englanniksi, sori. 
Lukuvinkki ja Kirja eriytetty eri tauluiksi, koska tulee vielä muun tyyppisiä vinkkejä, joissa omia sarakkeita(url) tai ei ole isbn:ää kuten kirjoilla-> tulisi muuten null-sisältäviä rivejä. 
Kirjailija omana tauluna, koska oletus että näitä voi olla useampi

**Comment by metinen** [comment]
Okei mietin tätä tänään vielä ja totesin, että ekaa sprinttiä varten tarvittiin varmaan vain testitietokanta missä yksi taulu (Vinkki, attribuutit kirjailija, otsikko, tyyppi). Eli lisäsin testitietokannan ohtuminiTEST.db, taulun Vinkki ja siihen kaksi datariviä.
Edellinen kommenttini ja docissa oleva tietomalli johon kommentti liittyy, voidaan varmaan käsitellä sprint2 suunnittelussa.
